export const detroitDynamoRouteManifest = [
  {
    path: '/detroit-dynamo',
    routerPath: 'index',
    label: 'Home',
    title: 'Detroit Dynamo | Elite Soccer Training',
    description: 'Detroit Dynamo is a Detroit-based soccer development pathway for private training, youth club growth, and future senior-team competition.',
    pillar: 'Platform',
    sitemap: true,
    priority: 1,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/training',
    routerPath: 'training',
    label: 'Training Academy',
    title: 'Detroit Dynamo Training Academy | Player Development',
    description: 'Private training, small-group training, team training, tryout prep, camps, clinics, and position-specific soccer development in Metro Detroit.',
    pillar: 'Training Academy',
    sitemap: true,
    priority: 0.9,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/fc',
    routerPath: 'fc',
    label: 'Club Pathway',
    title: 'Detroit Dynamo FC | Future Competitive Pathway',
    description: 'A future Detroit Dynamo club pathway connecting training, youth development, and senior men and women pro-development goals.',
    pillar: 'Club Pathway',
    sitemap: true,
    priority: 0.82,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/academy',
    routerPath: 'academy',
    label: 'Academy',
    title: 'Detroit Dynamo Academy | Development Model',
    description: 'The Detroit Dynamo development model for evaluation, technical detail, competitive habits, and progression into future team environments.',
    pillar: 'Training Academy',
    sitemap: true,
    priority: 0.78,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/youth-club',
    routerPath: 'youth-club',
    label: 'Youth Club',
    title: 'Detroit Dynamo Youth Club | Development Pathway',
    description: 'Youth soccer development pathway from U7-U8 foundation work through U13-U19 competitive club goals without claiming unconfirmed league membership.',
    pillar: 'Youth Club',
    sitemap: true,
    priority: 0.9,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/senior-men',
    routerPath: 'senior-men',
    label: "Senior Men",
    title: "Detroit Dynamo Senior Men | Future Pro-Development Pathway",
    description: "Future senior men's soccer pathway for serious Detroit-area players, including tryout interest, roster readiness, staff, schedules, and sponsors.",
    pillar: 'Senior Teams',
    sitemap: true,
    priority: 0.82,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/senior-women',
    routerPath: 'senior-women',
    label: "Senior Women",
    title: "Detroit Dynamo Senior Women | Future Pro-Development Pathway",
    description: "Future senior women's soccer pathway for serious Detroit-area players, including tryout interest, roster readiness, staff, schedules, and sponsors.",
    pillar: 'Senior Teams',
    sitemap: true,
    priority: 0.82,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/tryouts',
    routerPath: 'tryouts',
    label: 'Tryouts',
    title: 'Detroit Dynamo Tryouts | Register Interest',
    description: 'Register interest for youth tryouts, senior men and women pathways, or a training evaluation with Detroit Dynamo.',
    pillar: 'Registration',
    sitemap: true,
    priority: 0.9,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/teams',
    routerPath: 'teams',
    label: 'Teams',
    title: 'Detroit Dynamo Teams | Youth, Men, Women',
    description: 'Team directory and roster-ready structure for Detroit Dynamo youth teams, senior men, senior women, coaches, and managers.',
    pillar: 'Teams',
    sitemap: true,
    priority: 0.75,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/schedule-results',
    routerPath: 'schedule-results',
    label: 'Schedule & Results',
    title: 'Detroit Dynamo Schedule & Results',
    description: 'Schedule and results-ready page for future Detroit Dynamo youth and senior team fixtures once dates, opponents, and competitions are confirmed.',
    pillar: 'Teams',
    sitemap: true,
    priority: 0.7,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/camps-clinics',
    routerPath: 'camps-clinics',
    label: 'Camps & Clinics',
    title: 'Detroit Dynamo Camps & Clinics',
    description: 'Seasonal soccer camps, summer training, winter indoor training, speed and agility clinics, finishing clinics, and goalkeeper development.',
    pillar: 'Training Academy',
    sitemap: true,
    priority: 0.86,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/sponsors',
    routerPath: 'sponsors',
    label: 'Sponsors',
    title: 'Sponsor Detroit Dynamo',
    description: 'Sponsorship and local partnership opportunities for businesses that want to support Detroit Dynamo player development and future club growth.',
    pillar: 'Growth',
    sitemap: true,
    priority: 0.78,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/book',
    routerPath: 'book',
    label: 'Book Training',
    title: 'Book Detroit Dynamo Training',
    description: 'Request Detroit Dynamo training information or continue through the current Detroit Dynamo live booking flow while the rebrand remains in preview.',
    pillar: 'Training Academy',
    sitemap: true,
    priority: 0.9,
    changefreq: 'weekly',
  },
  {
    path: '/detroit-dynamo/results',
    routerPath: 'results',
    label: 'Development Results',
    title: 'Detroit Dynamo Results | Player Development',
    description: 'Player development outcomes Detroit Dynamo tracks: technique, decision-making, movement, confidence, and clearer training plans.',
    pillar: 'Training Academy',
    sitemap: true,
    priority: 0.65,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/contact',
    routerPath: 'contact',
    label: 'Contact',
    title: 'Contact Detroit Dynamo',
    description: 'Contact Detroit Dynamo for training inquiries, tryout interest, youth club questions, senior-team interest, sponsorship, or general information.',
    pillar: 'Registration',
    sitemap: true,
    priority: 0.82,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/about',
    routerPath: 'about',
    label: 'About',
    title: 'About Detroit Dynamo | Built in Detroit',
    description: 'Detroit Dynamo mission, vision, development philosophy, club standards, and long-term player pathway direction.',
    pillar: 'Platform',
    sitemap: true,
    priority: 0.74,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/brand',
    routerPath: 'brand',
    label: 'Brand',
    title: 'Detroit Dynamo Brand System | Internal Preview',
    description: 'Internal Detroit Dynamo brand, kits, digital identity, and visual system preview for rebrand comparison.',
    pillar: 'Internal',
    sitemap: false,
    priority: 0.2,
    changefreq: 'monthly',
  },
  {
    path: '/detroit-dynamo/admin-foundation',
    routerPath: 'admin-foundation',
    label: 'Admin Foundation',
    title: 'Detroit Dynamo Admin Foundation | Internal Preview',
    description: 'Internal Detroit Dynamo admin, data model, role, lead-routing, and Appwrite collection foundation preview.',
    pillar: 'Internal',
    sitemap: false,
    priority: 0.2,
    changefreq: 'monthly',
  },
];

export const detroitDynamoAliasRoutes = [
  {
    path: '/detroit-dynamo/club',
    routerPath: 'club',
    canonicalPath: '/detroit-dynamo/fc',
    reason: 'Friendly alternate name for the future club pathway.',
  },
  {
    path: '/detroit-dynamo/schedule',
    routerPath: 'schedule',
    canonicalPath: '/detroit-dynamo/schedule-results',
    reason: 'Short alias for schedule and results.',
  },
  {
    path: '/detroit-dynamo/camps',
    routerPath: 'camps',
    canonicalPath: '/detroit-dynamo/camps-clinics',
    reason: 'Short alias for camps and clinics.',
  },
  {
    path: '/detroit-dynamo-preview',
    routerPath: '/detroit-dynamo-preview',
    canonicalPath: '/detroit-dynamo',
    reason: 'Legacy preview entry point.',
  },
];

export const detroitDynamoRedirectPlan = [
  {
    from: '/',
    to: '/detroit-dynamo',
    timing: 'Only after full rebrand promotion',
    status: 'planned',
    note: 'Do not replace the current homepage while the preview is being compared.',
  },
  {
    from: '/book',
    to: '/detroit-dynamo/book',
    timing: 'After booking/payment migration',
    status: 'planned',
    note: 'Current live booking remains the source of truth until Dynamo payments/packages are approved.',
  },
  {
    from: '/lcfc',
    to: '/detroit-dynamo/fc',
    timing: 'After club-pathway promotion',
    status: 'planned',
    note: 'Use future-pathway language until league/team status is confirmed.',
  },
  {
    from: '/lcfc/tryouts',
    to: '/detroit-dynamo/tryouts',
    timing: 'After tryout intake migration',
    status: 'planned',
    note: 'Redirect only once Appwrite-backed tryout intake is live.',
  },
  {
    from: '/team',
    to: '/detroit-dynamo/teams',
    timing: 'After roster/team content migration',
    status: 'planned',
    note: 'Preserve existing team pages until confirmed rosters and staff exist.',
  },
  {
    from: '/team/schedule',
    to: '/detroit-dynamo/schedule-results',
    timing: 'After fixture/result confirmation',
    status: 'planned',
    note: 'Avoid publishing unconfirmed schedules or league commitments.',
  },
  {
    from: '/about',
    to: '/detroit-dynamo/about',
    timing: 'After legal/support/content migration',
    status: 'planned',
    note: 'Current company content stays live until full rebrand approval.',
  },
];

export const detroitDynamoSitemapRoutes = detroitDynamoRouteManifest.filter((route) => route.sitemap);
export const detroitDynamoAllRoutePaths = [
  ...detroitDynamoRouteManifest.map((route) => route.path),
  ...detroitDynamoAliasRoutes.map((route) => route.path),
];

export function getDetroitDynamoRouteMeta(pathname) {
  const alias = detroitDynamoAliasRoutes.find((route) => route.path === pathname);
  const targetPath = alias?.canonicalPath || pathname;
  return detroitDynamoRouteManifest.find((route) => route.path === targetPath) || null;
}
