export const detroitDynamoAdminRoles = [
  'Master Admin',
  'Club Director',
  'Training Director',
  'Coach',
  'Team Manager',
  'Registrar',
  'Media/Admin Staff',
];

export const detroitDynamoAdminModules = [
  'Players',
  'Parents/guardians',
  'Coaches',
  'Teams',
  'Age groups',
  'Training programs',
  'Training bookings',
  'Tryout registrations',
  'Camp registrations',
  'Payments/packages',
  'Waivers/forms',
  'News posts',
  'Sponsors',
  'Schedules/results',
  'Contact leads',
  'Website content sections',
];

const permission = (access, scope) => ({ access, scope });
const allModules = (access, scope) => Object.fromEntries(
  detroitDynamoAdminModules.map((module) => [module, permission(access, scope)]),
);
const buildRolePermissions = (role, purpose, modulePermissions, sensitiveControls = []) => ({
  role,
  purpose,
  sensitiveControls,
  permissions: detroitDynamoAdminModules.map((module) => ({
    module,
    access: modulePermissions[module]?.access || 'none',
    scope: modulePermissions[module]?.scope || 'No assigned access until role policy is expanded.',
  })),
});

export const detroitDynamoRolePermissionMatrix = [
  buildRolePermissions(
    'Master Admin',
    'Owns platform setup, payment/provider configuration, database provisioning, launch gates, and final promotion controls.',
    allModules('admin', 'Full administrative access for setup, launch approval, data correction, and emergency operations.'),
    ['Payment provider keys', 'Appwrite provisioning', 'Function deployment', 'SEO/redirect launch approval'],
  ),
  buildRolePermissions(
    'Club Director',
    'Owns club strategy, pathway standards, teams, staff structure, facilities, competition facts, and sponsor approvals.',
    {
      Players: permission('view', 'Review player pipeline and roster readiness across programs.'),
      'Parents/guardians': permission('view', 'View family contact context when needed for club operations.'),
      Coaches: permission('manage', 'Approve staff structure, public staff profiles, and coaching assignments.'),
      Teams: permission('manage', 'Create and approve youth, senior men, senior women, and pathway team structures.'),
      'Age groups': permission('manage', 'Define youth age-group roadmap and competitive pathway standards.'),
      'Training programs': permission('view', 'Review training-to-club alignment and public positioning.'),
      'Training bookings': permission('view', 'Review demand signals without editing coach-level session details.'),
      'Tryout registrations': permission('manage', 'Oversee tryout windows, senior pathway interest, and team-placement decisions.'),
      'Camp registrations': permission('view', 'Review camp demand and operational readiness.'),
      'Payments/packages': permission('view', 'Review package and dues readiness without provider-key access.'),
      'Waivers/forms': permission('view', 'Confirm waiver coverage before teams, camps, and tryouts launch.'),
      'News posts': permission('approve', 'Approve club announcements, league wording, staff news, and launch communications.'),
      Sponsors: permission('approve', 'Approve sponsor packages, logo use, and partnership claims.'),
      'Schedules/results': permission('manage', 'Approve fixtures, results, venues, and competition wording before publication.'),
      'Contact leads': permission('view', 'Review strategic inquiries and route high-priority opportunities.'),
      'Website content sections': permission('approve', 'Approve public brand, pathway, facility, league, and launch content.'),
    },
    ['League/facility claims', 'Staff/roster publication', 'Sponsor approvals'],
  ),
  buildRolePermissions(
    'Training Director',
    'Owns training academy programs, coach assignments, training packages, camps, clinics, and booking operations.',
    {
      Players: permission('contribute', 'Update training context, focus areas, and development notes when connected to programs.'),
      'Parents/guardians': permission('view', 'View guardian contacts needed for training coordination.'),
      Coaches: permission('contribute', 'Recommend coach assignments, specialties, and training capacity.'),
      Teams: permission('view', 'Review team needs that shape training programs.'),
      'Age groups': permission('view', 'Use age-group roadmap when building academy and camp offerings.'),
      'Training programs': permission('manage', 'Create and manage private, small-group, team-training, tryout-prep, camp, and clinic programs.'),
      'Training bookings': permission('manage', 'Manage training inquiry flow, coach availability, and booking lifecycle.'),
      'Tryout registrations': permission('view', 'Review evaluation demand and route players toward training or teams.'),
      'Camp registrations': permission('manage', 'Manage camp/clinic interest, capacity, dates, and training focus.'),
      'Payments/packages': permission('contribute', 'Propose packages and pricing for owner/payment approval.'),
      'Waivers/forms': permission('view', 'Confirm training and camp waiver coverage before sessions run.'),
      'News posts': permission('contribute', 'Draft training, camp, and clinic announcements.'),
      Sponsors: permission('view', 'Review training sponsor inventory and activation fit.'),
      'Schedules/results': permission('view', 'Review training/event calendars that affect team operations.'),
      'Contact leads': permission('manage', 'Own training, camp, clinic, and evaluation lead routing.'),
      'Website content sections': permission('contribute', 'Draft training academy and camp/clinic content.'),
    },
    ['Training package drafts', 'Camp/clinic registration readiness'],
  ),
  buildRolePermissions(
    'Coach',
    'Handles assigned player sessions, training notes, attendance context, and development feedback without broad admin control.',
    {
      Players: permission('view', 'View assigned players and relevant training context.'),
      'Parents/guardians': permission('view', 'View guardian contact context for assigned training sessions only.'),
      Coaches: permission('view', 'View coaching directory and staff context.'),
      Teams: permission('view', 'View assigned team or training group context.'),
      'Age groups': permission('view', 'Reference age-group standards for session planning.'),
      'Training programs': permission('view', 'View program structure and session focus expectations.'),
      'Training bookings': permission('contribute', 'Update assigned session notes, attendance, and training outcomes.'),
      'Tryout registrations': permission('view', 'View assigned evaluation context only.'),
      'Camp registrations': permission('view', 'View assigned camp/clinic roster context.'),
      'Payments/packages': permission('none', 'No payment or package administration.'),
      'Waivers/forms': permission('view', 'Confirm waiver status for assigned players before activity.'),
      'News posts': permission('none', 'No direct publication access.'),
      Sponsors: permission('none', 'No sponsor administration.'),
      'Schedules/results': permission('view', 'View assigned schedule context.'),
      'Contact leads': permission('none', 'No direct lead queue access.'),
      'Website content sections': permission('none', 'No website content administration.'),
    },
    ['Assigned-player privacy', 'Youth safeguarding boundaries'],
  ),
  buildRolePermissions(
    'Team Manager',
    'Coordinates team logistics, roster communications, schedules, results, and parent/team operations.',
    {
      Players: permission('contribute', 'Update roster logistics and team assignment context for assigned teams.'),
      'Parents/guardians': permission('contribute', 'Maintain guardian/team communication context for assigned teams.'),
      Coaches: permission('view', 'View assigned staff and coach contact context.'),
      Teams: permission('contribute', 'Maintain assigned team logistics, roster readiness, and manager notes.'),
      'Age groups': permission('view', 'Reference age-group and team standards.'),
      'Training programs': permission('view', 'Review program commitments that affect team calendars.'),
      'Training bookings': permission('view', 'View team-training bookings for assigned teams.'),
      'Tryout registrations': permission('view', 'Review assigned-team tryout and evaluation context.'),
      'Camp registrations': permission('view', 'Review camp participation for assigned players where relevant.'),
      'Payments/packages': permission('view', 'View team fee/payment status summaries without editing provider records.'),
      'Waivers/forms': permission('view', 'Confirm waiver completion for assigned team activities.'),
      'News posts': permission('contribute', 'Draft assigned-team updates, recaps, and announcements.'),
      Sponsors: permission('view', 'View sponsor placements relevant to team operations.'),
      'Schedules/results': permission('manage', 'Manage assigned-team fixtures, results, venue details, and recap inputs.'),
      'Contact leads': permission('view', 'View team-related inquiries routed by admin staff.'),
      'Website content sections': permission('contribute', 'Draft assigned-team roster, schedule, and manager content.'),
    },
    ['Assigned-team scope', 'Parent communication rules'],
  ),
  buildRolePermissions(
    'Registrar',
    'Owns player, guardian, tryout, waiver, camp registration, and eligibility records.',
    {
      Players: permission('manage', 'Manage player records, age groups, roster eligibility, and status.'),
      'Parents/guardians': permission('manage', 'Manage guardian contacts, relationships, and communication preferences.'),
      Coaches: permission('view', 'View coach/team assignments that affect registrations.'),
      Teams: permission('contribute', 'Update roster eligibility and registration status for teams.'),
      'Age groups': permission('contribute', 'Maintain birth-year and age-group registration context.'),
      'Training programs': permission('view', 'Review program requirements that affect player registration.'),
      'Training bookings': permission('view', 'View booking context for player/guardian records.'),
      'Tryout registrations': permission('manage', 'Own tryout intake, review status, invitations, waitlists, and archive flow.'),
      'Camp registrations': permission('manage', 'Own camp/clinic registrations, capacity, waitlists, and participant records.'),
      'Payments/packages': permission('view', 'View payment/package status needed for eligibility and registration.'),
      'Waivers/forms': permission('manage', 'Own waiver versions, signature status, expirations, and form completeness.'),
      'News posts': permission('none', 'No direct publication access.'),
      Sponsors: permission('none', 'No sponsor administration.'),
      'Schedules/results': permission('view', 'View schedules that affect registration and waiver readiness.'),
      'Contact leads': permission('manage', 'Own youth, tryout, camp, and registrar-routed contact leads.'),
      'Website content sections': permission('view', 'Review registration language but do not publish site content.'),
    },
    ['Minor data privacy', 'Guardian consent', 'Waiver status'],
  ),
  buildRolePermissions(
    'Media/Admin Staff',
    'Owns content workflow, sponsor/admin lead triage, media placeholders, news posts, and website section updates.',
    {
      Players: permission('view', 'View public-approved player context for stories only after release approval.'),
      'Parents/guardians': permission('none', 'No guardian data access unless explicitly routed by registrar.'),
      Coaches: permission('view', 'View public staff profile details and media-approved coach content.'),
      Teams: permission('view', 'View public team structure, schedule context, and approved roster details.'),
      'Age groups': permission('view', 'Reference age-group pathway language for content.'),
      'Training programs': permission('view', 'Reference program structure for content and lead routing.'),
      'Training bookings': permission('none', 'No booking administration.'),
      'Tryout registrations': permission('view', 'View aggregate tryout interest for communications planning only.'),
      'Camp registrations': permission('view', 'View aggregate camp interest for communications planning only.'),
      'Payments/packages': permission('none', 'No payment administration.'),
      'Waivers/forms': permission('none', 'No waiver administration.'),
      'News posts': permission('manage', 'Create and manage approved announcements, news, recaps, and launch content.'),
      Sponsors: permission('manage', 'Manage sponsor leads, logos, web links, placements, and approved activation content.'),
      'Schedules/results': permission('contribute', 'Draft schedule/result posts and media assets after team manager confirmation.'),
      'Contact leads': permission('manage', 'Triage general, sponsor, content, and public inquiry leads.'),
      'Website content sections': permission('manage', 'Manage approved website sections, proof slots, launch copy, and media placeholders.'),
    },
    ['Media release approval', 'Sponsor asset permissions', 'No payment/waiver access'],
  ),
];

export const detroitDynamoDataModels = {
  Player: [
    'id',
    'first_name',
    'last_name',
    'date_of_birth',
    'gender',
    'primary_position',
    'secondary_position',
    'current_club',
    'experience_level',
    'team_ids',
    'guardian_ids',
    'medical_notes',
    'waiver_status',
    'status',
  ],
  ParentGuardian: [
    'id',
    'first_name',
    'last_name',
    'email',
    'phone',
    'relationship',
    'player_ids',
    'communication_preferences',
  ],
  Coach: [
    'id',
    'first_name',
    'last_name',
    'email',
    'phone',
    'role',
    'licenses',
    'specialties',
    'team_ids',
    'program_ids',
    'bio',
    'photo_url',
    'background_check_status',
    'is_active',
  ],
  Team: [
    'id',
    'name',
    'program_pillar',
    'gender',
    'age_group',
    'season',
    'league_status',
    'coach_ids',
    'manager_ids',
    'player_ids',
    'tryout_status',
  ],
  Program: [
    'id',
    'name',
    'pillar',
    'description',
    'age_range',
    'skill_level',
    'season',
    'is_public',
    'cta_route',
  ],
  TrainingPackage: [
    'id',
    'name',
    'session_count',
    'duration_minutes',
    'price',
    'currency',
    'program_id',
    'is_visible',
  ],
  TrainingSession: [
    'id',
    'coach_id',
    'player_ids',
    'program_id',
    'starts_at',
    'ends_at',
    'location',
    'focus_areas',
    'status',
    'coach_notes',
  ],
  Booking: [
    'id',
    'player_id',
    'guardian_id',
    'coach_id',
    'training_package_id',
    'session_ids',
    'payment_id',
    'status',
    'requested_focus',
    'source_lead_id',
    'pipeline_status',
    'pipeline_owner_role',
    'pipeline_due_at',
    'pipeline_updated_at',
    'pipeline_last_note',
    'pipeline_event_count',
  ],
  TryoutRegistration: [
    'id',
    'player_name',
    'parent_guardian_name',
    'date_of_birth',
    'team_interest',
    'gender',
    'position',
    'current_previous_club',
    'experience_level',
    'email',
    'phone',
    'notes',
    'status',
    'source_lead_id',
    'pipeline_status',
    'pipeline_owner_role',
    'pipeline_due_at',
    'pipeline_updated_at',
    'pipeline_last_note',
    'pipeline_event_count',
  ],
  CampClinic: [
    'id',
    'name',
    'type',
    'season',
    'age_range',
    'starts_at',
    'ends_at',
    'location',
    'capacity',
    'price',
    'registration_status',
  ],
  Payment: [
    'id',
    'payer_profile_id',
    'amount',
    'currency',
    'provider',
    'provider_payment_id',
    'status',
    'related_record_type',
    'related_record_id',
  ],
  Waiver: [
    'id',
    'player_id',
    'guardian_id',
    'waiver_type',
    'version',
    'signed_at',
    'expires_at',
    'status',
  ],
  Sponsor: [
    'id',
    'business_name',
    'contact_name',
    'email',
    'phone',
    'package_interest',
    'logo_url',
    'website_url',
    'status',
    'source_lead_id',
    'pipeline_status',
    'pipeline_owner_role',
    'pipeline_due_at',
    'pipeline_updated_at',
    'pipeline_last_note',
    'pipeline_event_count',
  ],
  NewsPost: [
    'id',
    'title',
    'slug',
    'excerpt',
    'body',
    'hero_image_url',
    'category',
    'published_at',
    'status',
  ],
  MatchFixture: [
    'id',
    'team_id',
    'opponent',
    'starts_at',
    'venue',
    'home_away',
    'competition',
    'status',
  ],
  MatchResult: [
    'id',
    'fixture_id',
    'team_id',
    'opponent',
    'goals_for',
    'goals_against',
    'result',
    'recap_url',
  ],
  ContactLead: [
    'id',
    'lead_type',
    'contact_name',
    'email',
    'phone',
    'player_name',
    'organization',
    'message',
    'source_route',
    'status',
    'pipeline_status',
    'pipeline_owner_role',
    'pipeline_due_at',
    'pipeline_updated_at',
    'pipeline_last_note',
    'pipeline_event_count',
  ],
  AdminAuditEvent: [
    'id',
    'actor_user_id',
    'actor_role',
    'action',
    'target_model',
    'target_collection_id',
    'target_record_id',
    'previous_status',
    'next_status',
    'event_summary',
    'metadata_json',
    'ip_address',
    'created_at',
  ],
  AdminRoleAssignment: [
    'id',
    'actor_user_id',
    'email',
    'role',
    'status',
    'assigned_by_user_id',
    'assigned_at',
    'expires_at',
    'scope_note',
  ],
  StaffMember: [
    'id',
    'first_name',
    'last_name',
    'title',
    'department',
    'bio',
    'photo_url',
    'email',
    'display_order',
    'is_public',
  ],
};

export const detroitDynamoCollectionPlan = [
  {
    model: 'Player',
    collectionId: 'dd_players',
    phase: 'Phase 5',
    ownerRole: 'Registrar',
    notes: 'Core player profile for training, youth club, teams, waivers, and tryouts.',
  },
  {
    model: 'ParentGuardian',
    collectionId: 'dd_parent_guardians',
    phase: 'Phase 5',
    ownerRole: 'Registrar',
    notes: 'Guardian contact and consent relationship model for minors.',
  },
  {
    model: 'Coach',
    collectionId: 'dd_coaches',
    phase: 'Phase 5',
    ownerRole: 'Training Director',
    notes: 'Can map from existing coaches collection during promotion.',
  },
  {
    model: 'Team',
    collectionId: 'dd_teams',
    phase: 'Phase 5',
    ownerRole: 'Club Director',
    notes: 'Youth age groups, senior men, senior women, managers, coaches, and player assignments.',
  },
  {
    model: 'Program',
    collectionId: 'dd_programs',
    phase: 'Phase 5',
    ownerRole: 'Training Director',
    notes: 'Training academy, youth club, senior pathway, camps, and clinics.',
  },
  {
    model: 'TrainingPackage',
    collectionId: 'dd_training_packages',
    phase: 'Phase 5',
    ownerRole: 'Training Director',
    notes: 'Pricing/package layer before payments are connected.',
  },
  {
    model: 'TrainingSession',
    collectionId: 'dd_training_sessions',
    phase: 'Phase 5',
    ownerRole: 'Coach',
    notes: 'Booked or completed training sessions with focus areas and notes.',
  },
  {
    model: 'Booking',
    collectionId: 'dd_bookings',
    phase: 'Phase 5',
    ownerRole: 'Training Director',
    notes: 'Booking lifecycle from inquiry to paid/completed session.',
  },
  {
    model: 'TryoutRegistration',
    collectionId: 'dd_tryout_registrations',
    phase: 'Phase 4',
    ownerRole: 'Registrar',
    notes: 'Youth, senior men, senior women, and training evaluation interest.',
  },
  {
    model: 'CampClinic',
    collectionId: 'dd_camps_clinics',
    phase: 'Phase 5',
    ownerRole: 'Training Director',
    notes: 'Seasonal camps, finishing clinics, goalkeeper work, winter indoor, speed/agility.',
  },
  {
    model: 'Payment',
    collectionId: 'dd_payments',
    phase: 'Phase 5',
    ownerRole: 'Master Admin',
    notes: 'Payment references only until Stripe/PayPal products are approved.',
  },
  {
    model: 'Waiver',
    collectionId: 'dd_waivers',
    phase: 'Phase 5',
    ownerRole: 'Registrar',
    notes: 'Training, youth club, camp, media, medical, and team participation waivers.',
  },
  {
    model: 'Sponsor',
    collectionId: 'dd_sponsors',
    phase: 'Phase 4',
    ownerRole: 'Media/Admin Staff',
    notes: 'Sponsor leads, package interest, approved logos, and website placements.',
  },
  {
    model: 'NewsPost',
    collectionId: 'dd_news_posts',
    phase: 'Phase 5',
    ownerRole: 'Media/Admin Staff',
    notes: 'Announcements, tryouts, camps, sponsors, rosters, match recaps, and media posts.',
  },
  {
    model: 'MatchFixture',
    collectionId: 'dd_match_fixtures',
    phase: 'Phase 5',
    ownerRole: 'Team Manager',
    notes: 'Published only after opponent, venue, team, date, and competition are confirmed.',
  },
  {
    model: 'MatchResult',
    collectionId: 'dd_match_results',
    phase: 'Phase 5',
    ownerRole: 'Team Manager',
    notes: 'Scores and recaps connected to confirmed fixtures.',
  },
  {
    model: 'ContactLead',
    collectionId: 'dd_contact_leads',
    phase: 'Phase 4',
    ownerRole: 'Media/Admin Staff',
    notes: 'General, training, sponsor, team, camp, and youth interest routing.',
  },
  {
    model: 'AdminAuditEvent',
    collectionId: 'dd_admin_audit_events',
    phase: 'Phase 5',
    ownerRole: 'Master Admin',
    notes: 'Append-only operational audit trail for protected admin actions, pipeline transitions, safeguarding-sensitive mutations, and future launch controls.',
  },
  {
    model: 'AdminRoleAssignment',
    collectionId: 'dd_admin_role_assignments',
    phase: 'Phase 5',
    ownerRole: 'Master Admin',
    notes: 'Trusted role grants for authenticated Detroit Dynamo admin users before protected module reads or mutations are enabled.',
  },
  {
    model: 'StaffMember',
    collectionId: 'dd_staff_members',
    phase: 'Phase 5',
    ownerRole: 'Club Director',
    notes: 'Public staff directory and internal operational roles.',
  },
];

const collectionIdByModel = Object.fromEntries(
  detroitDynamoCollectionPlan.map((item) => [item.model, item.collectionId]),
);

const collectionsForModels = (models) => models.map((model) => collectionIdByModel[model]).filter(Boolean);
const moduleSlug = (value) => String(value || '')
  .toLowerCase()
  .replace(/&/g, 'and')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-+|-+$/g, '');

const adminModule = ({
  module,
  purpose,
  primaryModels,
  ownerRoles,
  launchPhase,
  status,
  enabledActions,
  blockedUntil,
  sourceRoutes = [],
}) => ({
  module,
  slug: moduleSlug(module),
  purpose,
  primaryModels,
  collectionIds: collectionsForModels(primaryModels),
  ownerRoles,
  launchPhase,
  status,
  enabledActions,
  blockedUntil,
  sourceRoutes,
});

export const detroitDynamoAdminModuleRegistry = [
  adminModule({
    module: 'Players',
    purpose: 'Track player profiles from training leads, youth club interest, tryouts, rosters, waivers, and future team placement.',
    primaryModels: ['Player', 'TryoutRegistration', 'Team', 'Waiver'],
    ownerRoles: ['Registrar', 'Club Director'],
    launchPhase: 'Phase 5',
    status: 'intake_ready_after_backend',
    enabledActions: ['Review player leads', 'Assign status', 'Connect guardians', 'Prepare roster eligibility'],
    blockedUntil: 'Appwrite dd_players is provisioned and registrar workflows are approved.',
    sourceRoutes: ['/detroit-dynamo/tryouts', '/detroit-dynamo/youth-club'],
  }),
  adminModule({
    module: 'Parents/guardians',
    purpose: 'Manage guardian contact, consent relationships, communication preferences, and minor-player family context.',
    primaryModels: ['ParentGuardian', 'Player', 'Waiver'],
    ownerRoles: ['Registrar'],
    launchPhase: 'Phase 5',
    status: 'intake_ready_after_backend',
    enabledActions: ['Review guardian records', 'Connect players', 'Track consent readiness', 'Route family communication'],
    blockedUntil: 'Guardian consent language and privacy rules are approved.',
    sourceRoutes: ['/detroit-dynamo/tryouts', '/detroit-dynamo/youth-club'],
  }),
  adminModule({
    module: 'Coaches',
    purpose: 'Maintain coaching staff, specialties, licenses, background-check status, assignments, and public staff visibility.',
    primaryModels: ['Coach', 'StaffMember', 'Team', 'Program'],
    ownerRoles: ['Training Director', 'Club Director'],
    launchPhase: 'Phase 5',
    status: 'admin_dashboard_needed',
    enabledActions: ['Create coach profiles', 'Assign programs', 'Assign teams', 'Review background-check status'],
    blockedUntil: 'Staff facts, safeguarding process, and public bios are approved.',
    sourceRoutes: ['/detroit-dynamo/about', '/detroit-dynamo/training'],
  }),
  adminModule({
    module: 'Teams',
    purpose: 'Create youth, senior men, senior women, and pathway team records with coaches, managers, rosters, and tryout status.',
    primaryModels: ['Team', 'Player', 'Coach', 'StaffMember'],
    ownerRoles: ['Club Director', 'Team Manager', 'Registrar'],
    launchPhase: 'Phase 5',
    status: 'admin_dashboard_needed',
    enabledActions: ['Create team shells', 'Assign coaches', 'Assign managers', 'Prepare roster cards'],
    blockedUntil: 'Team naming, roster policy, and competition/facility facts are approved.',
    sourceRoutes: ['/detroit-dynamo/teams', '/detroit-dynamo/senior-men', '/detroit-dynamo/senior-women'],
  }),
  adminModule({
    module: 'Age groups',
    purpose: 'Manage birth-year cohorts, U7-U8 foundation, U9-U12 pre-academy, and U13-U19 competitive pathway structure.',
    primaryModels: ['Team', 'Program', 'Player'],
    ownerRoles: ['Club Director', 'Registrar'],
    launchPhase: 'Phase 5',
    status: 'admin_dashboard_needed',
    enabledActions: ['Define age-group cohorts', 'Map players by birth year', 'Publish pathway language', 'Review capacity'],
    blockedUntil: 'Youth club development roadmap and tryout structure are approved.',
    sourceRoutes: ['/detroit-dynamo/youth-club', '/detroit-dynamo/academy'],
  }),
  adminModule({
    module: 'Training programs',
    purpose: 'Manage private training, small groups, team training, tryout prep, position work, camps, and clinic program definitions.',
    primaryModels: ['Program', 'TrainingPackage', 'CampClinic'],
    ownerRoles: ['Training Director'],
    launchPhase: 'Phase 5',
    status: 'admin_dashboard_needed',
    enabledActions: ['Create programs', 'Draft package options', 'Set public visibility', 'Connect booking CTAs'],
    blockedUntil: 'Program pricing, capacity, location, and coach assignment rules are approved.',
    sourceRoutes: ['/detroit-dynamo/training', '/detroit-dynamo/camps-clinics'],
  }),
  adminModule({
    module: 'Training bookings',
    purpose: 'Route training inquiries into booking leads, coach availability review, session planning, and payment handoff.',
    primaryModels: ['Booking', 'TrainingSession', 'TrainingPackage', 'ContactLead'],
    ownerRoles: ['Training Director', 'Coach'],
    launchPhase: 'Phase 4',
    status: 'intake_ready_after_backend',
    enabledActions: ['Review booking leads', 'Assign coach follow-up', 'Capture requested focus', 'Prepare session records'],
    blockedUntil: 'Appwrite dd_bookings is provisioned and live booking/payment policy is approved.',
    sourceRoutes: ['/detroit-dynamo/book', '/detroit-dynamo/training'],
  }),
  adminModule({
    module: 'Tryout registrations',
    purpose: 'Manage youth, senior men, senior women, and training evaluation registrations from public interest forms.',
    primaryModels: ['TryoutRegistration', 'Player', 'Team', 'ParentGuardian'],
    ownerRoles: ['Registrar', 'Club Director'],
    launchPhase: 'Phase 4',
    status: 'intake_ready_after_backend',
    enabledActions: ['Review registrations', 'Set status', 'Route by pathway', 'Prepare invite/waitlist decisions'],
    blockedUntil: 'Appwrite intake is deployed and tryout operating dates are approved.',
    sourceRoutes: ['/detroit-dynamo/tryouts', '/detroit-dynamo/senior-men', '/detroit-dynamo/senior-women'],
  }),
  adminModule({
    module: 'Camp registrations',
    purpose: 'Manage camp and clinic interest, capacity, waitlists, age ranges, dates, locations, and participant readiness.',
    primaryModels: ['CampClinic', 'Player', 'ParentGuardian', 'Waiver'],
    ownerRoles: ['Training Director', 'Registrar'],
    launchPhase: 'Phase 5',
    status: 'admin_dashboard_needed',
    enabledActions: ['Create camp shells', 'Track interest', 'Manage capacity', 'Confirm waiver readiness'],
    blockedUntil: 'Camp dates, facilities, pricing, and waiver rules are approved.',
    sourceRoutes: ['/detroit-dynamo/camps-clinics'],
  }),
  adminModule({
    module: 'Payments/packages',
    purpose: 'Manage training packages, camp pricing, team fees, sponsor packages, payment references, refunds, and checkout readiness.',
    primaryModels: ['Payment', 'TrainingPackage', 'CampClinic', 'Sponsor'],
    ownerRoles: ['Master Admin', 'Training Director'],
    launchPhase: 'Phase 5',
    status: 'external_gate',
    enabledActions: ['Draft packages', 'Map provider products', 'Review payment status', 'Prepare refund rules'],
    blockedUntil: 'Stripe/PayPal products, exact prices, refund terms, and owner approval are confirmed.',
    sourceRoutes: ['/detroit-dynamo/training', '/detroit-dynamo/sponsors'],
  }),
  adminModule({
    module: 'Waivers/forms',
    purpose: 'Manage training, tryout, camp, youth club, media, medical, travel, and adult participation waiver readiness.',
    primaryModels: ['Waiver', 'Player', 'ParentGuardian', 'CampClinic'],
    ownerRoles: ['Registrar', 'Master Admin'],
    launchPhase: 'Phase 5',
    status: 'external_gate',
    enabledActions: ['Draft waiver versions', 'Track signature status', 'Review expirations', 'Gate participation readiness'],
    blockedUntil: 'Legal waiver text and consent workflow are approved.',
    sourceRoutes: ['/detroit-dynamo/tryouts', '/detroit-dynamo/camps-clinics'],
  }),
  adminModule({
    module: 'News posts',
    purpose: 'Draft, review, approve, and publish club announcements, tryouts, camps, staff news, sponsors, rosters, and match recaps.',
    primaryModels: ['NewsPost', 'StaffMember', 'Sponsor', 'MatchResult'],
    ownerRoles: ['Media/Admin Staff', 'Club Director'],
    launchPhase: 'Phase 5',
    status: 'admin_dashboard_needed',
    enabledActions: ['Draft posts', 'Approve claims', 'Schedule publication', 'Archive old posts'],
    blockedUntil: 'Content approval workflow and media-release rules are approved.',
    sourceRoutes: ['/detroit-dynamo', '/detroit-dynamo/about'],
  }),
  adminModule({
    module: 'Sponsors',
    purpose: 'Track sponsor leads, packages, logo assets, website placements, approvals, and local business partnership follow-up.',
    primaryModels: ['Sponsor', 'ContactLead', 'NewsPost'],
    ownerRoles: ['Media/Admin Staff', 'Club Director'],
    launchPhase: 'Phase 4',
    status: 'intake_ready_after_backend',
    enabledActions: ['Review sponsor leads', 'Track package interest', 'Approve logos', 'Prepare partnership content'],
    blockedUntil: 'Sponsor packages, logo permissions, and publication rules are approved.',
    sourceRoutes: ['/detroit-dynamo/sponsors'],
  }),
  adminModule({
    module: 'Schedules/results',
    purpose: 'Manage fixtures, venues, competition labels, results, recaps, and team schedule publication readiness.',
    primaryModels: ['MatchFixture', 'MatchResult', 'Team', 'NewsPost'],
    ownerRoles: ['Team Manager', 'Club Director'],
    launchPhase: 'Phase 5',
    status: 'external_gate',
    enabledActions: ['Create fixture drafts', 'Confirm venues', 'Publish results', 'Connect recaps'],
    blockedUntil: 'Teams, competitions, opponents, facilities, and schedules are confirmed.',
    sourceRoutes: ['/detroit-dynamo/schedule-results', '/detroit-dynamo/results'],
  }),
  adminModule({
    module: 'Contact leads',
    purpose: 'Triage general, training, youth, senior-team, camp, sponsor, and operational inquiries into owner queues.',
    primaryModels: ['ContactLead', 'Booking', 'TryoutRegistration', 'Sponsor'],
    ownerRoles: ['Media/Admin Staff', 'Training Director', 'Registrar'],
    launchPhase: 'Phase 4',
    status: 'intake_ready_after_backend',
    enabledActions: ['Review leads', 'Assign owner', 'Set status', 'Export follow-up queue'],
    blockedUntil: 'Appwrite intake is deployed and admin notification/follow-up workflow is approved.',
    sourceRoutes: ['/detroit-dynamo/contact', '/detroit-dynamo/book'],
  }),
  adminModule({
    module: 'Website content sections',
    purpose: 'Manage approved brand copy, pathway sections, proof slots, staff modules, sponsor placements, and launch metadata.',
    primaryModels: ['NewsPost', 'StaffMember', 'Sponsor', 'Program'],
    ownerRoles: ['Media/Admin Staff', 'Club Director'],
    launchPhase: 'Phase 5',
    status: 'external_gate',
    enabledActions: ['Draft content sections', 'Approve launch copy', 'Update proof slots', 'Prepare sitemap/redirect promotion'],
    blockedUntil: 'Owner approves final brand launch, SEO, redirects, public claims, and noindex removal.',
    sourceRoutes: ['/detroit-dynamo', '/detroit-dynamo/brand', '/detroit-dynamo/about'],
  }),
];

export const detroitDynamoAdminModuleDetailRoutes = detroitDynamoAdminModuleRegistry.map((item) => (
  `/admin/detroit-dynamo/modules/${item.slug}`
));

export const detroitDynamoLeadRouting = {
  contact: {
    destinationModel: 'ContactLead',
    destinationModels: ['ContactLead'],
    collectionIds: collectionsForModels(['ContactLead']),
    ownerRole: 'Media/Admin Staff',
    nextAction: 'Qualify inquiry and assign to training, registrar, sponsor, or club director queue.',
  },
  training: {
    destinationModel: 'ContactLead + Booking',
    destinationModels: ['ContactLead', 'Booking'],
    collectionIds: collectionsForModels(['ContactLead', 'Booking']),
    ownerRole: 'Training Director',
    nextAction: 'Confirm program fit, coach availability, location, and booking path.',
  },
  youth: {
    destinationModel: 'Player + ParentGuardian + TryoutRegistration',
    destinationModels: ['Player', 'ParentGuardian', 'TryoutRegistration'],
    collectionIds: collectionsForModels(['Player', 'ParentGuardian', 'TryoutRegistration']),
    ownerRole: 'Registrar',
    nextAction: 'Group by birth year, county, level, and future age-group cohort.',
  },
  tryout: {
    destinationModel: 'Player + ParentGuardian + TryoutRegistration',
    destinationModels: ['Player', 'ParentGuardian', 'TryoutRegistration'],
    collectionIds: collectionsForModels(['Player', 'ParentGuardian', 'TryoutRegistration']),
    ownerRole: 'Registrar',
    nextAction: 'Review player profile and route to youth, senior men, senior women, or training evaluation.',
  },
  men: {
    destinationModel: 'Player + TryoutRegistration + Team',
    destinationModels: ['Player', 'TryoutRegistration', 'Team'],
    collectionIds: collectionsForModels(['Player', 'TryoutRegistration', 'Team']),
    ownerRole: 'Club Director',
    nextAction: 'Track senior men interest without claiming league membership.',
  },
  women: {
    destinationModel: 'Player + TryoutRegistration + Team',
    destinationModels: ['Player', 'TryoutRegistration', 'Team'],
    collectionIds: collectionsForModels(['Player', 'TryoutRegistration', 'Team']),
    ownerRole: 'Club Director',
    nextAction: 'Track senior women interest without claiming league membership.',
  },
  sponsor: {
    destinationModel: 'Sponsor + ContactLead',
    destinationModels: ['Sponsor', 'ContactLead'],
    collectionIds: collectionsForModels(['Sponsor', 'ContactLead']),
    ownerRole: 'Media/Admin Staff',
    nextAction: 'Qualify business, package interest, assets, budget, and activation fit.',
  },
};

export const detroitDynamoLeadPipelineStages = [
  {
    status: 'new',
    label: 'New intake',
    ownerAction: 'Confirm the lead type, source route, contact information, and required player or business context.',
    maxAgeHours: 4,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['triaged', 'closed_duplicate'],
    adminModules: ['Contact leads'],
  },
  {
    status: 'triaged',
    label: 'Owner assigned',
    ownerAction: 'Assign the correct director, registrar, training owner, or sponsor/media owner and set the next follow-up channel.',
    maxAgeHours: 24,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['contacted', 'closed_not_fit'],
    adminModules: ['Contact leads', 'Tryout registrations', 'Training bookings', 'Sponsors'],
  },
  {
    status: 'contacted',
    label: 'First contact made',
    ownerAction: 'Send the first email, call, or text, then log the response window and any missing details.',
    maxAgeHours: 48,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['awaiting_response', 'evaluation_scheduled', 'package_discussion', 'closed_not_fit'],
    adminModules: ['Contact leads', 'Training bookings', 'Tryout registrations', 'Sponsors'],
  },
  {
    status: 'awaiting_response',
    label: 'Awaiting response',
    ownerAction: 'Keep the lead open with one clear follow-up date, then close or schedule if the player, parent, or business responds.',
    maxAgeHours: 96,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['contacted', 'evaluation_scheduled', 'closed_not_fit'],
    adminModules: ['Contact leads', 'Training bookings', 'Tryout registrations', 'Sponsors'],
  },
  {
    status: 'package_discussion',
    label: 'Package discussion',
    ownerAction: 'Discuss training packages, camp interest, sponsor inventory, or team-fee readiness without collecting payment until packages are approved.',
    maxAgeHours: 96,
    appliesTo: ['training', 'sponsor', 'contact'],
    nextStatuses: ['evaluation_scheduled', 'converted', 'closed_not_fit'],
    adminModules: ['Training bookings', 'Sponsors', 'Payments/packages'],
  },
  {
    status: 'evaluation_scheduled',
    label: 'Evaluation or meeting scheduled',
    ownerAction: 'Confirm the session, tryout, sponsor call, or program-fit meeting and connect the lead to the expected record draft.',
    maxAgeHours: 72,
    appliesTo: ['training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['invited_or_waitlisted', 'converted', 'closed_no_show'],
    adminModules: ['Training bookings', 'Tryout registrations', 'Sponsors', 'Players'],
  },
  {
    status: 'invited_or_waitlisted',
    label: 'Decision pending',
    ownerAction: 'Record invite, waitlist, roster, package, camp, or sponsor-package decision after owner review.',
    maxAgeHours: 120,
    appliesTo: ['youth', 'tryout', 'men', 'women', 'training', 'sponsor'],
    nextStatuses: ['converted', 'closed_not_fit'],
    adminModules: ['Tryout registrations', 'Teams', 'Training bookings', 'Sponsors'],
  },
  {
    status: 'converted',
    label: 'Converted to active record',
    ownerAction: 'Connect the lead to active player, booking, tryout, team, sponsor, payment, or waiver records once backend modules are live.',
    maxAgeHours: 168,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['archived'],
    adminModules: ['Players', 'Training bookings', 'Tryout registrations', 'Teams', 'Sponsors', 'Payments/packages', 'Waivers/forms'],
  },
  {
    status: 'closed_not_fit',
    label: 'Closed',
    ownerAction: 'Close with reason, preserve source context, and avoid publishing any unsupported player, roster, league, or sponsor claim.',
    maxAgeHours: 168,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['archived'],
    adminModules: ['Contact leads'],
  },
  {
    status: 'closed_duplicate',
    label: 'Closed duplicate',
    ownerAction: 'Merge duplicate context into the oldest useful record and keep only one active follow-up owner.',
    maxAgeHours: 24,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['archived'],
    adminModules: ['Contact leads'],
  },
  {
    status: 'closed_no_show',
    label: 'Closed no-show',
    ownerAction: 'Record the missed evaluation, meeting, or call and reopen only if the family, player, or business requests a new time.',
    maxAgeHours: 72,
    appliesTo: ['training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['archived', 'evaluation_scheduled'],
    adminModules: ['Training bookings', 'Tryout registrations', 'Sponsors'],
  },
  {
    status: 'archived',
    label: 'Archived',
    ownerAction: 'Retain the source and outcome for reporting while removing the lead from active follow-up queues.',
    maxAgeHours: 720,
    appliesTo: ['contact', 'training', 'youth', 'tryout', 'men', 'women', 'sponsor'],
    nextStatuses: ['new'],
    adminModules: ['Contact leads'],
  },
];

export const detroitDynamoLeadPipelineByType = Object.fromEntries(
  Object.entries(detroitDynamoLeadRouting).map(([leadType, routing]) => [
    leadType,
    {
      leadType,
      ownerRole: routing.ownerRole,
      collectionIds: routing.collectionIds,
      destinationModels: routing.destinationModels,
      defaultStatus: 'new',
      requiredStages: detroitDynamoLeadPipelineStages
        .filter((stage) => stage.appliesTo.includes(leadType))
        .map((stage) => stage.status),
    },
  ]),
);

export const detroitDynamoLaunchReadiness = [
  {
    category: 'Backend/Data',
    status: 'planned',
    ownerRole: 'Master Admin',
    evidenceNeeded: [
      'Approved isolated dd_* collection plan',
      'Valid Appwrite project credentials',
      'Verified detroitDynamoLeadIntake fixtures for all public form variants',
      'Deployed detroitDynamoLeadIntake function',
      'Verified detroitDynamoLeadPipelineAction fixtures for authenticated status changes',
      'Verified detroitDynamoAdminModuleRead fixtures for protected module reads',
      'Verified detroitDynamoAdminRoleGrantAction fixtures for Master Admin role grant management',
      'Verified detroitDynamoAdminModuleWriteAction fixtures for protected module writes',
      'Active dd_admin_role_assignments grants for every live admin role',
      'Public form writes tested from production preview',
    ],
    nextAction: 'Review the scaffold, replace expired credentials, run the dry run, then apply the Appwrite provisioner.',
    promotionGate: 'Data backend live',
  },
  {
    category: 'Payments/Packages',
    status: 'pending_confirmation',
    ownerRole: 'Master Admin',
    evidenceNeeded: [
      'Approved training package pricing',
      'Camp, tryout, club dues, and sponsor package rules',
      'Stripe or PayPal product mapping',
      'Refund, cancellation, and failed-payment handling',
    ],
    nextAction: 'Confirm business pricing and provider choice before connecting checkout or package purchase flows.',
    promotionGate: 'Payments approved',
  },
  {
    category: 'Waivers/Legal',
    status: 'pending_confirmation',
    ownerRole: 'Registrar',
    evidenceNeeded: [
      'Youth participation waiver',
      'Medical consent and emergency contact language',
      'Media release and privacy language',
      'Adult participation and team-travel consent where needed',
    ],
    nextAction: 'Have the owner and appropriate legal reviewer approve waiver text before collecting signatures.',
    promotionGate: 'Waivers approved',
  },
  {
    category: 'League/Competition',
    status: 'future_pathway',
    ownerRole: 'Club Director',
    evidenceNeeded: [
      'Confirmed senior league acceptance before naming membership',
      'Confirmed youth league placement before naming competition',
      'Roster, staff, insurance, and rules compliance',
      'Published schedule only after opponents, dates, and venues are confirmed',
    ],
    nextAction: 'Keep all UPSL, UPSL Women, and youth-league language framed as a goal until written confirmation exists.',
    promotionGate: 'League facts confirmed',
  },
  {
    category: 'Facilities/Operations',
    status: 'pending_confirmation',
    ownerRole: 'Club Director',
    evidenceNeeded: [
      'Confirmed training locations and permitted field access',
      'Facility calendars for training, tryouts, camps, and matches',
      'Insurance and safety requirements',
      'Weather, cancellation, and communication procedures',
    ],
    nextAction: 'Confirm facility partners and operating rules before publishing location-specific commitments.',
    promotionGate: 'Facilities confirmed',
  },
  {
    category: 'Content/Brand Promotion',
    status: 'preview_only',
    ownerRole: 'Media/Admin Staff',
    evidenceNeeded: [
      'Approved Detroit Dynamo launch copy',
      'Confirmed staff, testimonials, sponsor logos, news, and media',
      'SEO metadata, sitemap, redirects, and social images approved',
      'Detroit Dynamo migration or preservation plan signed off',
    ],
    nextAction: 'Keep the Dynamo site noindex and isolated until promotion timing, redirects, and real content are approved.',
    promotionGate: 'Launch content approved',
  },
];

export const detroitDynamoPromotionGates = [
  {
    gate: 'Legacy public route preservation',
    status: 'passing_in_preview',
    requiredEvidence: 'Root LC routes, booking, auth, forms, navigation, manifest, and footer continue to work before launch.',
    nextAction: 'Keep running current-site isolation checks before every promotion decision.',
  },
  {
    gate: 'Data backend live',
    status: 'planned',
    requiredEvidence: 'All required dd_* collections exist, permissions are reviewed, and public forms persist to Appwrite.',
    nextAction: 'Provision after final field review and valid credentials are available.',
  },
  {
    gate: 'Payments approved',
    status: 'pending_confirmation',
    requiredEvidence: 'Products, packages, taxes/fees, refunds, and settlement handling are approved by the business owner.',
    nextAction: 'Map approved packages to checkout flows and payment records.',
  },
  {
    gate: 'Waivers approved',
    status: 'pending_confirmation',
    requiredEvidence: 'Participation, medical, media, privacy, and travel consent language is approved before signature capture.',
    nextAction: 'Connect waiver versions to registrations, bookings, camps, and teams.',
  },
  {
    gate: 'League and facility facts confirmed',
    status: 'future_pathway',
    requiredEvidence: 'No current league, fixture, roster, facility, or staff claim is published without confirmation.',
    nextAction: 'Maintain future-pathway language until official documents or owner-approved facts are available.',
  },
  {
    gate: 'SEO and redirect launch approved',
    status: 'preview_only',
    requiredEvidence: 'Canonical routes, sitemap, metadata, Open Graph assets, and old-route redirect timing are approved.',
    nextAction: 'Remove noindex only when Detroit Dynamo is the approved public brand.',
  },
];

export const detroitDynamoBackendActivationSteps = [
  {
    step: 1,
    title: 'Run Local Backend Preflight',
    ownerRole: 'Master Admin',
    command: 'npm run preflight:dynamo-backend',
    evidence: 'Backend preflight report shows schema, function config, function source, pipeline-action fixture coverage, admin-module-read fixture coverage, admin-role-grant fixture coverage, admin-module-write fixture coverage, and env-key presence without printing secrets.',
    nextAction: 'Resolve any failing local checks before attempting networked backend work.',
  },
  {
    step: 2,
    title: 'Review Appwrite Collection Plan',
    ownerRole: 'Master Admin',
    command: 'npm run plan:dynamo-appwrite',
    evidence: 'Plan confirms the 18 requested operational dd_* collections plus admin audit event and admin role assignment collections with expected attributes, indexes, access policies, and public/function write paths.',
    nextAction: 'Approve fields, indexes, owner roles, public-form destinations, and audit-event retention before applying.',
  },
  {
    step: 3,
    title: 'Provision Isolated Collections',
    ownerRole: 'Master Admin',
    command: 'npm run provision:dynamo-appwrite -- --apply',
    evidence: 'Appwrite contains the dd_* collections, attributes, indexes, and permissions required by the Detroit Dynamo model.',
    nextAction: 'Use valid Appwrite credentials and do not mutate legacy Detroit Dynamo collections.',
  },
  {
    step: 4,
    title: 'Configure Function Variables',
    ownerRole: 'Master Admin',
    command: 'node scripts/configure-functions.mjs',
    evidence: 'detroitDynamoLeadIntake, detroitDynamoLeadPipelineAction, detroitDynamoAdminModuleRead, detroitDynamoAdminRoleGrantAction, and detroitDynamoAdminModuleWriteAction have APPWRITE_API_KEY configured in Appwrite without exposing the key in logs or client code.',
    nextAction: 'Confirm function variables after replacing any expired Appwrite key; set DETROIT_DYNAMO_BOOTSTRAP_ADMIN_USER_ID before first live Master Admin grant.',
  },
  {
    step: 5,
    title: 'Deploy Lead Intake, Pipeline, Module Read, Role Grant, and Module Write Functions',
    ownerRole: 'Master Admin',
    command: 'appwrite push functions --all',
    evidence: 'detroitDynamoLeadIntake, detroitDynamoLeadPipelineAction, detroitDynamoAdminModuleRead, detroitDynamoAdminRoleGrantAction, and detroitDynamoAdminModuleWriteAction are deployed and enabled with database/document scopes from appwrite.json.',
    nextAction: 'Deploy only after preflight, provisioning, and function variable configuration pass.',
  },
  {
    step: 6,
    title: 'Enable Appwrite Intake in Admin',
    ownerRole: 'Media/Admin Staff',
    command: 'Use /admin/detroit-dynamo Form Intake Mode',
    evidence: 'Protected admin mode is switched from Local Preview to Appwrite Intake after backend deployment.',
    nextAction: 'Keep local preview fallback available until production-preview form submissions are verified.',
  },
  {
    step: 7,
    title: 'Submit Production-Preview Test Leads and Pipeline Actions',
    ownerRole: 'Registrar',
    command: 'npm run verify:dynamo-intake-contract && npm run verify:dynamo-pipeline-actions, then submit training, tryout, youth, senior, sponsor, and contact forms from /detroit-dynamo/*',
    evidence: 'Pipeline action fixtures validate locally, test submissions create ContactLead plus expected TryoutRegistration or Sponsor records in the dd_* collections, and authenticated pipeline actions update allowed statuses.',
    nextAction: 'Verify no console errors, no broken success states, valid status transitions, and clear admin routing for every lead type.',
  },
  {
    step: 8,
    title: 'Lock Promotion Gate Evidence',
    ownerRole: 'Club Director',
    command: 'npm run audit:dynamo-goal',
    evidence: 'Goal audit still passes implemented scope and keeps external gates visible until payments, waivers, facilities, and league facts are confirmed.',
    nextAction: 'Do not publish sitemap/redirect changes or enable external-gated operations until all promotion gates are approved.',
  },
];

export const detroitDynamoExternalConfirmationRegister = [
  {
    area: 'Payments & Packages',
    status: 'pending_confirmation',
    ownerRole: 'Master Admin',
    relatedModels: ['TrainingPackage', 'Payment', 'Booking', 'CampClinic', 'Sponsor'],
    requiredFacts: [
      'Approved private, small-group, team-training, camp, tryout, dues, and sponsor package pricing',
      'Selected payment provider, checkout flow, refund policy, and failed-payment handling',
      'Tax/fee treatment, discount policy, and settlement ownership',
      'Admin reporting needs for packages, payments, refunds, and outstanding balances',
    ],
    publishRule: 'Do not publish checkout links or exact package commitments until pricing and provider setup are approved.',
    nextAction: 'Owner approves package matrix, provider, refund rules, and admin payment fields.',
  },
  {
    area: 'Waivers & Legal',
    status: 'pending_confirmation',
    ownerRole: 'Registrar',
    relatedModels: ['Waiver', 'Player', 'ParentGuardian', 'TryoutRegistration', 'CampClinic'],
    requiredFacts: [
      'Youth participation waiver and medical consent language',
      'Media release, privacy/terms language, and adult participation waiver',
      'Travel, emergency contact, and camp/clinic consent requirements',
      'Versioning, expiration, guardian signature, and retention rules',
    ],
    publishRule: 'Do not collect signatures or present legal text as final until owner/legal review is complete.',
    nextAction: 'Prepare approved waiver versions and map each form/program to the right waiver requirement.',
  },
  {
    area: 'League & Competition Facts',
    status: 'future_pathway',
    ownerRole: 'Club Director',
    relatedModels: ['Team', 'MatchFixture', 'MatchResult', 'NewsPost'],
    requiredFacts: [
      'Confirmed senior men league acceptance before naming current UPSL or similar membership',
      'Confirmed senior women league acceptance before naming current UPSL Women or similar membership',
      'Confirmed youth league placement before naming current youth competition',
      'Fixture, opponent, venue, roster, staff, and competition rules confirmed before publication',
    ],
    publishRule: 'Use future-pathway language until written league or competition confirmation exists.',
    nextAction: 'Collect official league/competition documentation and owner-approved public wording.',
  },
  {
    area: 'Facilities & Operations',
    status: 'pending_confirmation',
    ownerRole: 'Club Director',
    relatedModels: ['TrainingSession', 'CampClinic', 'MatchFixture', 'Program'],
    requiredFacts: [
      'Confirmed training locations, field permits, indoor facility access, and match venues',
      'Calendar availability for private training, camps, tryouts, youth teams, and senior teams',
      'Insurance, safety, weather, cancellation, check-in, and emergency procedures',
      'Published location names, addresses, parking/access notes, and facility partner permissions',
    ],
    publishRule: 'Do not publish facility commitments, addresses, or schedules until operating access is confirmed.',
    nextAction: 'Confirm facility partners, operating rules, insurance requirements, and calendar windows.',
  },
  {
    area: 'Staff, Rosters & Safeguarding',
    status: 'pending_confirmation',
    ownerRole: 'Club Director',
    relatedModels: ['Coach', 'StaffMember', 'Team', 'Player'],
    requiredFacts: [
      'Confirmed staff names, roles, bios, licenses, photos, and public contact rules',
      'Background check, safeguarding, and youth communication standards',
      'Approved rosters, player photos, bios, statuses, and parent/player release permissions',
      'Team manager assignments and internal access levels',
    ],
    publishRule: 'Do not publish staff, roster, or player bio details until permissions and verification are complete.',
    nextAction: 'Collect staff/roster approvals and map internal roles to admin permissions.',
  },
  {
    area: 'Sponsors, Media & Content Proof',
    status: 'preview_only',
    ownerRole: 'Media/Admin Staff',
    relatedModels: ['Sponsor', 'NewsPost', 'ContactLead'],
    requiredFacts: [
      'Approved sponsor packages, logos, website links, activation inventory, and display permissions',
      'Real testimonials, player stories, media clips, and partner quotes',
      'Launch announcements, news categories, editorial approval workflow, and image rights',
      'SEO/social assets, redirect timing, sitemap/robots publication, and current-site migration wording',
    ],
    publishRule: 'Keep proof slots as placeholders until real quotes, sponsor assets, and content rights are approved.',
    nextAction: 'Approve sponsor assets, proof content, launch copy, and publication workflow before promotion.',
  },
];
